version: "3"
services:
  frontend:
    image: node:12.18.2
    working_dir: /srv/frontend/public
    command: bash -c "yarn && yarn start"
    depends_on:
      - api
    volumes:
      - "./frontend:/srv/frontend/public"
    ports:
      - 3000:3000

  api:
    image: node:12.18.2
    working_dir: /srv/app
    depends_on:
      - database
    command: bash -c "yarn && yarn start"
    ports:
      - 3020:3020
    volumes:
      - "./api:/srv/app"

  scm:
    image: node:12.18.2
    working_dir: /srv/app
    command: bash -c "yarn && yarn start"
    ports:
      - 3030:3030
    volumes:
      - "./scm:/srv/app"

  database:
    env_file: .mongo.env
    image: mongo
    ports:
      - 27017:27017
