apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: staging
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lucassm02/quest-code-backend-frontend:{{ Values.image.tag }}
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: {{ .Values.container.port }}
