---
apiVersion: v1
kind: Secret
metadata:
  name: backend-user
  namespace: production
type: Opaque
data:
  JWT_SECRET: YW55LXNlY3JldAo=
  MONGO_URI: YW55LXNlY3JldAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-user
  namespace: homologation
type: Opaque
data:
  JWT_SECRET: YW55LXNlY3JldAo=
  MONGO_URI: YW55LXNlY3JldAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-scm
  namespace: production
type: Opaque
data:
  GITHUB_CLIENT_SECRET: YW55LXNlY3JldAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-scm
  namespace: homologation
type: Opaque
data:
  GITHUB_CLIENT_SECRET: YW55LXNlY3JldAo=
---

