apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scm-deployment
  labels:
    app: backend-scm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-scm
  template:
    metadata:
      labels:
        app: backend-scm
    spec:
      containers:
        - name: backend-scm
          image: lucassm02/quest-code-backend-scm:1.1
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-scm
                  key: NODE_ENV

            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: backend-scm
                  key: GITHUB_CLIENT_ID

            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-scm
                  key: GITHUB_CLIENT_SECRET
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 3030
